git config --global color.diff.old "red strike"
git config --global color.diff.new "green italic"
git config --global diff.compactionHeuristic "true"
git config --global user.name "John Montgomery"
git config --global alias.co "checkout"
git config --global alias.br "branch"
git config --global alias.st "status"
